services:
  vaultwarden:
    image: vaultwarden/server:latest
    container_name: vaultwarden
    volumes:
      - vaultwarden:/data/
    ports:
      - $PORT:80
    restart: unless-stopped

volumes:
  vaultwarden: {}