services:
  server:
    build: .
    image: node-18:1.0
    container_name: node-18
    volumes:
      - data:/9ecbf/data

volumes:
  data:
    name: node-18
    driver: local
    driver_opts:
      type: none
      o: bind
      device: "~/data/node-18"
