services:
  server:
    build:
      context: .
      network: host
    image: node-18:1.0
    container_name: node-18
    volumes:
      - data:/9ecbf/data
    network_mode: host

volumes:
  data:
    name: node-18
    driver: local
    driver_opts:
      type: none
      o: bind
      device: "~/data/node-18"
