#!/bin/bash

export SSH_PORT=2222

[ ! -f "$BASH_SOURCE.lock" ] && apt update \
    && apt upgrade -y \
    && apt install openssh-server -y \
    && echo -e "\nPort $SSH_PORT" >> /etc/ssh/sshd_config \
    && echo -e "\nListenAddress 0.0.0.0" >> /etc/ssh/sshd_config \
    && echo -e "\nPasswordAuthentication yes" >> /etc/ssh/sshd_config \
    && echo -e "\nPermitEmptyPasswords yes" >> /etc/ssh/sshd_config \
    && service ssh start \
    && echo "1" > $BASH_SOURCE.lock

echo "$(date) | INFO | SSH server started at $(hostname):$SSH_PORT."
echo "$(date) | WARN | Please log in with a username other than $(whoami)."